# Generated by Django 4.2.1 on 2023-05-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(default=None, upload_to='media'),
        ),
    ]
